# filepath: c:\Users\himan\User Application\VS Code\Bandipur\bandipur-house-website\admin\config.yml
backend:
  name: github
  repo: himan/bandipur-house-website # IMPORTANT: Replace with your username/repo
  branch: main # Or the branch your GitHub Pages site is built from (e.g., gh-pages)
  # Optional: Specify site_domain if using Netlify Identity + custom domain
  # site_domain: your-custom-domain.com

media_folder: "assets/images/uploads" # Optional: Where to store uploaded images
public_folder: "/assets/images/uploads" # Optional: Public path to media folder

collections:
  - name: "events_json"
    label: "Events" # Label shown in the CMS UI
    files: # Specify we are editing a single file
      - label: "Events List"
        name: "events" # Internal identifier for this file config
        file: "_data/events.json" # Path to the JSON file relative to the repo root
        fields: # Define the structure of the file
          - label: "Events"
            name: "event_items" # The key in the JSON file holding the array of events
            widget: "list" # Use a list widget for the array
            summary: "{{fields.title}}" # How to display items in the list UI
            fields: # Fields for each item in the list (each event)
              - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, format: "YYYY-MM-DD" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }